import type { Program } from './types'

export const objectSampleProgram: Program = {
  version: 1,
  nodes: [
    {
      id: 'point-class',
      type: 'class',
      text: 'Point(x, y)',
      position: { x: 20, y: 20 },
    },
    {
      id: 'point-move',
      type: 'method',
      text: 'move',
      position: { x: 20, y: 220 },
    },
    {
      id: 'move-dx',
      type: 'input',
      text: 'dx',
      position: { x: 20, y: 330 },
    },
    {
      id: 'move-dy',
      type: 'input',
      text: 'dy',
      position: { x: 20, y: 440 },
    },
    {
      id: 'move-x',
      type: 'process',
      text: 'x <- x + dx\ny <- y + dy',
      position: { x: 20, y: 550 },
    },
    {
      id: 'move-return',
      type: 'return',
      text: 'self',
      position: { x: 20, y: 680 },
    },
    {
      id: 'point-repr',
      type: 'method',
      text: '__repr__',
      position: { x: 300, y: 220 },
    },
    {
      id: 'repr-return',
      type: 'return',
      text: '"Point(" + x + ", " + y + ")"',
      position: { x: 300, y: 330 },
    },
    {
      id: 'object-main',
      type: 'function',
      text: 'main',
      position: { x: 560, y: 20 },
    },
    {
      id: 'make-point',
      type: 'process',
      text: 'p <- Point(2, 3)\nsame_point <- p',
      position: { x: 560, y: 130 },
    },
    {
      id: 'move-point',
      type: 'call',
      text: 'p.move(5, -1)',
      position: { x: 560, y: 260 },
    },
    {
      id: 'show-point',
      type: 'output',
      text: 'p',
      position: { x: 560, y: 370 },
    },
    {
      id: 'show-x',
      type: 'output',
      text: 'p.x',
      position: { x: 560, y: 480 },
    },
    {
      id: 'show-y',
      type: 'output',
      text: 'p.y',
      position: { x: 560, y: 590 },
    },
    {
      id: 'object-return',
      type: 'return',
      text: 'p',
      position: { x: 560, y: 700 },
    },
  ],
  edges: [
    { id: 'edge-point-move', source: 'point-class', target: 'point-move' },
    { id: 'edge-point-repr', source: 'point-class', target: 'point-repr' },
    { id: 'edge-repr-return', source: 'point-repr', target: 'repr-return' },
    { id: 'edge-move-dx', source: 'point-move', target: 'move-dx' },
    { id: 'edge-dx-dy', source: 'move-dx', target: 'move-dy' },
    { id: 'edge-dy-x', source: 'move-dy', target: 'move-x' },
    { id: 'edge-x-return', source: 'move-x', target: 'move-return' },
    { id: 'edge-main-make', source: 'object-main', target: 'make-point' },
    { id: 'edge-make-move', source: 'make-point', target: 'move-point' },
    { id: 'edge-move-show', source: 'move-point', target: 'show-point' },
    { id: 'edge-show-x', source: 'show-point', target: 'show-x' },
    { id: 'edge-x-y-output', source: 'show-x', target: 'show-y' },
    { id: 'edge-output-return', source: 'show-y', target: 'object-return' },
  ],
}
